service: serverless-ruby-starter

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
